# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemtype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Question'), (1, 'Answer'), (2, 'Book')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
