# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20160511_1346'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Название',
            new_name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(),
        ),
    ]
